### ISSUE TITLE
The build succeeds, the install also, but I cannot run the software

### ISSUE THREAD

**Issue by lopippo** [PiotrRadzinski/envemind#3]
Greetings, still me :-)

On my Debian GNU/Linux box, I have finally run these commands:

```
% python setup.py build (ok)
% sudo python setup.py install
```

This latest command's output:

```
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating envemind.egg-info
writing envemind.egg-info/PKG-INFO
writing dependency_links to envemind.egg-info/dependency_links.txt
writing requirements to envemind.egg-info/requires.txt
writing top-level names to envemind.egg-info/top_level.txt
writing manifest file 'envemind.egg-info/SOURCES.txt'
reading manifest file 'envemind.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'envemind.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/envemind
copying build/lib/envemind/__init__.py -> build/bdist.linux-x86_64/egg/envemind
copying build/lib/envemind/main.py -> build/bdist.linux-x86_64/egg/envemind
byte-compiling build/bdist.linux-x86_64/egg/envemind/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/envemind/main.py to main.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying envemind.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying envemind.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying envemind.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying envemind.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying envemind.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/envemind-0.0.1-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing envemind-0.0.1-py3.10.egg
Copying envemind-0.0.1-py3.10.egg to /usr/local/lib/python3.10/dist-packages
Adding envemind 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/envemind-0.0.1-py3.10.egg
Processing dependencies for envemind==0.0.1
Searching for pyteomics
Reading https://pypi.org/simple/pyteomics/
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/1e/bf/90a9281eda518293521f52d44aa1168f92a34d365b5e96b61112667fa2e3/pyteomics-4.5.6-py2.py3-none-any.whl#sha256=0e279c085370e8085c84997adb8f9e16425facf2d088ba80f2b7e6bcb59cfebe
Best match: pyteomics 4.5.6
Processing pyteomics-4.5.6-py2.py3-none-any.whl
Installing pyteomics-4.5.6-py2.py3-none-any.whl to /usr/local/lib/python3.10/dist-packages
Adding pyteomics 4.5.6 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/pyteomics-4.5.6-py3.10.egg
Searching for SciPy==1.8.1
Best match: SciPy 1.8.1
Adding SciPy 1.8.1 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for numpy==1.21.5
Best match: numpy 1.21.5
Adding numpy 1.21.5 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.10 script to /usr/local/bin
Installing f2py3.11 script to /usr/local/bin

Using /usr/lib/python3/dist-packages
Searching for IsoSpecPy==2.2.1
Best match: IsoSpecPy 2.2.1
Adding IsoSpecPy 2.2.1 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for envemind==0.0.1

```

Then I fired a python console and ran this command:

```
>>> import envemind as ev
```

with this output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rusconi/devel/envemind/envemind/__init__.py", line 1, in <module>
    from envemind.main import formula, monoisotopic_mass_prediction, mzMLread
  File "/home/rusconi/devel/envemind/envemind/main.py", line 9, in <module>
    from pyteomics import mzml
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/mzml.py", line 82, in <module>
    from . import xml, auxiliary as aux, _schema_defaults
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/xml.py", line 39, in <module>
    from .auxiliary import FileReader, PyteomicsError, basestring, _file_obj, HierarchicalOffsetIndex
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/auxiliary/__init__.py", line 6, in <module>
    from .patch import Version as _Version
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/auxiliary/patch.py", line 14, in <module>
    pv = pd.version.version
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'version'. Did you mean: '__version'?
```

I have pandas installed an running fine (I use it for a project):

 python3-pandas           1.3.5

It looks like the problem is in pyteomics, that I have installed using pip install pyteomics:

```
% pip show pyteomics                                                                                                                                                                                        git:(master|…4 
Name: pyteomics
Version: 4.5.6
Summary: A framework for proteomics data analysis.
Home-page: http://pyteomics.readthedocs.io
Author: Anton Goloborodko & Lev Levitsky
Author-email: pyteomics@googlegroups.com
License: License :: OSI Approved :: Apache Software License
Location: /home/rusconi/.local/lib/python3.10/site-packages
Requires: 
Required-by: envemind
```

So my question is: are you aware of version requirement for the dependencies of envemind ?

Sincerely,
Filippo Rusconi

**Comment by PiotrRadzinski** [comment]
Again, I summon our installation/version expert -- @michalsta :)
Sincerely,
Piotr
