### ISSUE TITLE
import envemind in python3 fails

### ISSUE THREAD

**Issue by lopippo** [PiotrRadzinski/envemind#4]
Greetings,
still trying to run the example from the README.md:

```
% python                                                                                                                                                                                                    git:(master|…2 
Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(ins)>>> import envemind
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rusconi/devel/envemind/envemind/envemind/__init__.py", line 1, in <module>
    from envemind.main import formula, monoisotopic_mass_prediction, mzMLread
  File "/home/rusconi/devel/envemind/envemind/envemind/main.py", line 9, in <module>
    from pyteomics import mzml
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/mzml.py", line 82, in <module>
    from . import xml, auxiliary as aux, _schema_defaults
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/xml.py", line 39, in <module>
    from .auxiliary import FileReader, PyteomicsError, basestring, _file_obj, HierarchicalOffsetIndex
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/auxiliary/__init__.py", line 6, in <module>
    from .patch import Version as _Version
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/auxiliary/patch.py", line 14, in <module>
    pv = pd.version.version
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'version'. Did you mean: '__version'?
```

These are the versions of the python modules involved:

python3-pandas      1.3.5 (system-wide Debian package)
pyteomics                   4.5.6 (pip installed, not packaged in Debian)

Any idea what might go awry ?

Sincerely,
Filippo

PS By the way, congratulations for the article, you might want to expose it in the README :-)

**Comment by michalsta** [comment]
OK, try as I might, I can't reproduce this so far on my Gentoo.  Which version of Debian are you running? I might try a debootstap chroot with that...
Also, can you do a "from pyteomics import mzml"?

**Comment by lopippo** [comment]
Greetings, Michał,
I am running Debian testing. 
> Also, can you do a "from pyteomics import mzml"?

Well, no: 

```
% python
Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(ins)>>> from pyteomics import xml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/xml.py", line 39, in <module>
    from .auxiliary import FileReader, PyteomicsError, basestring, _file_obj, HierarchicalOffsetIndex
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/auxiliary/__init__.py", line 6, in <module>
    from .patch import Version as _Version
  File "/home/rusconi/.local/lib/python3.10/site-packages/pyteomics/auxiliary/patch.py", line 14, in <module>
    pv = pd.version.version
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'version'. Did you mean: '__version'?
```

However, I tried to fix the version problem by commenting out the following lines (file site-packages/pyteomics/auxiliary/patch.py) since the version I have is largely > 0.17...

# else:
    # if hasattr(pd, '_version'):
        # pv = pd._version.get_versions()['version']
    # else:
        # pv = pd.version.version
    # if Version(pv) < Version('0.17'):
        # pd.DataFrame.sort_values = pd.DataFrame.sort


and I could get through the sample script on the README.md file to the result: 16940.9241718775. Is this the correct result you get?

It thus looks like the problem is in pyteomics... If the result above is correct, we might consider closing the issue?
Sincerely,
Filippo
